### ISSUE TITLE
CSS Transition

### ISSUE THREAD

**Issue by jamesliu96** [jamesliu96/Damoo#3]
TODO: Test feature using CSS `transition` to do animation. Stylesheet can be dynamically generated by js.

**Comment by nareix** [comment]
CSS transition 在 Chrome 不大给力，在 Safari 还可以。目前来说还是 canvas 好。

**Comment by nareix** [comment]
刚刚实测了一下，确认 css transition 是比现有方法慢很多的，插入的 DOM 节点一多 CPU 就爆了，还是现有的方法好。
